### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by byDave251** [reem-codes/japana#1]
When I tried to install, I encountered this problem.

```
 Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from japana) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from japana)
```

![image](https://user-images.githubusercontent.com/25853767/60590836-526fdd80-9d9d-11e9-84e2-53627f6f9c10.png)

**Comment by reem-codes** [comment]
fixed it :D
